//! Score IR → lcvgc DSL 文字列の emitter。
//!
//! MVP の出力ルール:
//! 1. ヘッダコメント (生成元の表示)
//! 2. `device gen_device { port GEN_PORT }`
//! 3. Drum トラックがあれば `kit gen_kit { ... }`
//! 4. 各 Melodic トラック毎に `instrument <name> { device gen_device, channel N }`
//! 5. 各トラック毎に `clip <name> { ... }` を 1 つ生成 (`[bars N]` 自動算出)
//! 6. `tempo N`
//! 7. すべての clip を含む `scene gen_scene { ... }`
//! 8. `play gen_scene`
//!
//! 同時発音 (同 tick の複数ノート) は `[a b c]:dur` の和音記法でまとめる。
//! 音価は 16 分音符グリッドに量子化し、不要なものはタイ (`x:8 x:16`) で繋ぐ。
//! `LoopBlock` は `(...)*count` で展開。
//!
//! Emits lcvgc DSL from a `Score`. The MVP output structure is described
//! above. Notes are quantized onto a 16th-note grid; loop blocks become
//! `(...)*count`; drum tracks are emitted with the step-sequencer notation.

use super::quantize::quantize_ticks;
use super::score::{Event, Score, Track, TrackKind};
use super::GeneratorError;

/// Score を lcvgc DSL 文字列に変換する。
///
/// Converts a Score into an lcvgc DSL string.
///
/// # Errors
/// 表現不能な構造を含む場合 `GeneratorError::Emit` を返す (現在の MVP では
/// 殆ど発生しない)。
pub fn emit(score: &Score) -> Result<String, GeneratorError> {
    let mut out = String::new();
    emit_header(score, &mut out);
    emit_device(&mut out);
    emit_kit_if_drum(score, &mut out);
    emit_instruments(score, &mut out);
    emit_clips(score, &mut out)?;
    emit_tempo(score, &mut out);
    emit_scene(score, &mut out);
    emit_play(&mut out);
    Ok(out)
}

/// 生成元情報のヘッダコメントを書き出す。
/// Writes the header comment.
fn emit_header(score: &Score, out: &mut String) {
    out.push_str("// generated by lcvgc-gen\n");
    if let Some(title) = &score.title {
        out.push_str("// title: ");
        out.push_str(title);
        out.push('\n');
    }
    out.push_str(&format!(
        "// time signature: {}/{}\n",
        score.time_signature.numerator, score.time_signature.denominator
    ));
    out.push('\n');
}

/// `device gen_device { port GEN_PORT }` を書き出す。
///
/// ユーザは生成された DSL の `port` を環境に合わせて書き換える前提。
/// Writes the placeholder device block.
fn emit_device(out: &mut String) {
    out.push_str("device gen_device {\n  port GEN_PORT\n}\n\n");
}

/// Drum トラックが含まれていれば GM ドラムマップに沿った `kit` を 1 つ書き出す。
/// Writes a kit block if the score has any drum track.
fn emit_kit_if_drum(score: &Score, out: &mut String) {
    let has_drum = score.tracks.iter().any(|t| t.kind == TrackKind::Drum);
    if !has_drum {
        return;
    }
    // GM ドラムマップから、score 内で実際に出現するノートだけ kit に登録する。
    let mut used: Vec<u8> = score
        .tracks
        .iter()
        .filter(|t| t.kind == TrackKind::Drum)
        .flat_map(|t| iter_notes(&t.events))
        .map(|(_, _, midi_note, _)| midi_note)
        .collect();
    used.sort_unstable();
    used.dedup();

    out.push_str("kit gen_kit {\n  device gen_device\n");
    for midi_note in used {
        if let Some(label) = gm_drum_label(midi_note) {
            let (name, oct) = midi_to_note_name(midi_note);
            out.push_str(&format!(
                "  {} {{ channel 10, note {}:{} }}\n",
                label, name, oct
            ));
        }
    }
    out.push_str("}\n\n");
}

/// 各 Melodic トラックに対し instrument を書き出す。
/// Writes one instrument per melodic track.
fn emit_instruments(score: &Score, out: &mut String) {
    for t in &score.tracks {
        if t.kind != TrackKind::Melodic {
            continue;
        }
        out.push_str(&format!(
            "instrument {} {{\n  device gen_device\n  channel {}\n}}\n\n",
            t.name, t.midi_channel
        ));
    }
}

/// 各トラックを `clip` として書き出す。
/// Writes one clip per track.
fn emit_clips(score: &Score, out: &mut String) -> Result<(), GeneratorError> {
    for t in &score.tracks {
        let bars = bars_for_track(t, score);
        let clip_name = format!("{}_clip", t.name);
        match t.kind {
            TrackKind::Melodic => {
                emit_melodic_clip(&clip_name, t, score, bars, out)?;
            }
            TrackKind::Drum => {
                emit_drum_clip(&clip_name, t, score, bars, out)?;
            }
        }
    }
    Ok(())
}

/// 1 つの Melodic clip を書き出す。
///
/// 同時発音 (同 start_tick) のノートは `[a b c]:dur` に集約する。
/// `LoopBlock` は `(...)*count` で展開する。
///
/// Emits a single melodic clip.
fn emit_melodic_clip(
    clip_name: &str,
    track: &Track,
    score: &Score,
    bars: u32,
    out: &mut String,
) -> Result<(), GeneratorError> {
    out.push_str(&format!("clip {} [bars {}] {{\n", clip_name, bars));
    let mut cursor: u64 = 0;
    let mut body = String::new();
    body.push_str(&format!("  {}", track.name));
    emit_event_sequence(&track.events, score, &mut cursor, &mut body, &track.name)?;
    body.push('\n');
    out.push_str(&body);
    out.push_str("}\n\n");
    Ok(())
}

/// 1 つの Drum clip を書き出す。
///
/// `resolution 16` 固定で、16 分音符グリッドにヒットを配置する。
///
/// Emits a single drum clip with `resolution 16`.
fn emit_drum_clip(
    clip_name: &str,
    track: &Track,
    score: &Score,
    bars: u32,
    out: &mut String,
) -> Result<(), GeneratorError> {
    let steps_per_bar: u32 = 16; // resolution 16 + 4/4 を前提
    let total_steps = (steps_per_bar * bars) as usize;
    let ticks_per_step = (score.ppq / 4).max(1) as u64;

    // (midi_note, [step1, step2, ...]) のマップを作る。
    let mut per_note: std::collections::BTreeMap<u8, Vec<char>> = std::collections::BTreeMap::new();
    for (start, _end, midi_note, velocity) in iter_notes(&track.events) {
        let step = (start / ticks_per_step) as usize;
        if step >= total_steps {
            continue;
        }
        let row = per_note
            .entry(midi_note)
            .or_insert_with(|| vec!['.'; total_steps]);
        row[step] = velocity_to_hit_symbol(velocity);
    }

    out.push_str(&format!("clip {} [bars {}] {{\n", clip_name, bars));
    out.push_str("  use gen_kit\n");
    out.push_str("  resolution 16\n");
    for (midi_note, row) in per_note {
        if let Some(label) = gm_drum_label(midi_note) {
            let row_str: String = row.into_iter().collect();
            out.push_str(&format!("  {} {}\n", label, row_str));
        }
    }
    out.push_str("}\n\n");
    Ok(())
}

/// 量子化したヒット symbol を返す。
///
/// `velocity >= 110` → アクセント (`X`)
/// `velocity <= 60`  → ゴースト (`o`)
/// それ以外         → 通常 (`x`)
fn velocity_to_hit_symbol(velocity: u8) -> char {
    if velocity >= 110 {
        'X'
    } else if velocity <= 60 {
        'o'
    } else {
        'x'
    }
}

/// Melodic イベント列を文字列化して body に追記する。
///
/// イベントは `start_tick` 昇順でソートしたうえで、同 tick のノートは和音
/// (`[a b c]`) としてまとめる。`LoopBlock` は `(...)*count` で展開し、内部の
/// 並びにも同じロジックを再帰適用する。
///
/// Serializes a sequence of melodic events into the clip body.
fn emit_event_sequence(
    events: &[Event],
    score: &Score,
    cursor: &mut u64,
    out: &mut String,
    _track_name: &str,
) -> Result<(), GeneratorError> {
    // 1) ノートと LoopBlock を時系列で取り出す
    let mut items: Vec<&Event> = events.iter().collect();
    items.sort_by_key(|e| e.start_tick());

    // 2) 同 tick のノートをまとめながら順に書き出す
    let mut i = 0;
    while i < items.len() {
        match items[i] {
            Event::Note { start_tick, .. } => {
                // 休符で隙間を埋める
                if *start_tick > *cursor {
                    let gap = *start_tick - *cursor;
                    write_rest(out, gap, score.ppq);
                    *cursor = *start_tick;
                }
                // 同 tick のノートを集約 (和音検出)
                let mut chord: Vec<(u8, u64)> = Vec::new(); // (midi, end_tick)
                while i < items.len() {
                    match items[i] {
                        Event::Note {
                            start_tick: s,
                            end_tick,
                            midi_note,
                            ..
                        } if *s == *start_tick => {
                            chord.push((*midi_note, *end_tick));
                            i += 1;
                        }
                        _ => break,
                    }
                }
                let chord_end = chord.iter().map(|(_, e)| *e).max().unwrap_or(*start_tick);
                let dur_ticks = chord_end.saturating_sub(*start_tick);
                write_chord_or_note(out, &chord, dur_ticks, score.ppq);
                *cursor = chord_end;
            }
            Event::LoopBlock {
                start_tick,
                events: inner,
                count,
            } => {
                // ループブロック先頭まで休符で進める
                if *start_tick > *cursor {
                    let gap = *start_tick - *cursor;
                    write_rest(out, gap, score.ppq);
                    *cursor = *start_tick;
                }
                // 内部イベントを文字列化して `( ... )*N` で囲む
                let mut inner_out = String::new();
                let mut inner_cursor: u64 = *start_tick;
                emit_event_sequence(inner, score, &mut inner_cursor, &mut inner_out, _track_name)?;
                let one_iter_ticks = inner_cursor.saturating_sub(*start_tick);
                out.push_str(" (");
                out.push_str(inner_out.trim_start());
                out.push_str(&format!(" )*{}", count));
                *cursor += one_iter_ticks * (*count as u64);
                i += 1;
            }
        }
    }
    Ok(())
}

/// 休符を書き出す (隙間 tick → `r:duration` 列)。
fn write_rest(out: &mut String, ticks: u64, ppq: u32) {
    let (tokens, _, _) = quantize_ticks(ticks, ppq);
    for t in tokens {
        out.push_str(" r:");
        out.push_str(t.as_str());
    }
}

/// 単音 or 和音を書き出す。
///
/// `chord` が 1 要素なら単音 `note:oct:dur`、複数なら `[a:o b:o c:o]:dur` 記法。
/// 音価は最長要素の長さで量子化し、複数 token になる場合はタイで繋ぐ。
fn write_chord_or_note(out: &mut String, chord: &[(u8, u64)], dur_ticks: u64, ppq: u32) {
    let (tokens, _, _) = quantize_ticks(dur_ticks, ppq);
    // 単音 or 和音の文字列を作る (音高部分のみ)
    let pitch_part = if chord.len() == 1 {
        let (midi, _) = chord[0];
        let (n, o) = midi_to_note_name(midi);
        format!("{}:{}", n, o)
    } else {
        let inner: Vec<String> = chord
            .iter()
            .map(|(m, _)| {
                let (n, o) = midi_to_note_name(*m);
                format!("{}:{}", n, o)
            })
            .collect();
        format!("[{}]", inner.join(" "))
    };
    // 1 つ目のトークンは音価付き、残りはタイ (同音名繰り返し) で表現
    let mut first = true;
    for tok in tokens {
        if first {
            out.push(' ');
            out.push_str(&format!("{}:{}", pitch_part, tok.as_str()));
            first = false;
        } else {
            // タイ: lcvgc DSL では明示記号が無いため、同音をもう一度書く
            // (近似)
            out.push(' ');
            out.push_str(&format!("{}:{}", pitch_part, tok.as_str()));
        }
    }
}

/// テンポを書き出す。
fn emit_tempo(score: &Score, out: &mut String) {
    out.push_str(&format!("tempo {}\n\n", score.initial_bpm.round() as i32));
}

/// 全 clip を含む scene を書き出す。
fn emit_scene(score: &Score, out: &mut String) {
    out.push_str("scene gen_scene {\n");
    for t in &score.tracks {
        out.push_str(&format!("  {}_clip\n", t.name));
    }
    out.push_str("}\n\n");
}

/// 自動再生コマンド。
fn emit_play(out: &mut String) {
    out.push_str("play gen_scene\n");
}

/// トラックの bar 数を算出する。
///
/// `total_ticks / (numerator * ppq * 4 / denominator)` の切り上げ。最小 1 bar。
fn bars_for_track(track: &Track, score: &Score) -> u32 {
    let last = track_last_tick(&track.events);
    let bar_ticks = bar_ticks(score);
    if bar_ticks == 0 {
        return 1;
    }
    let bars = last.div_ceil(bar_ticks);
    bars.max(1) as u32
}

/// 1 bar あたりの tick 数 (`numerator * ppq * 4 / denominator`)。
fn bar_ticks(score: &Score) -> u64 {
    let num = score.time_signature.numerator as u64;
    let den = score.time_signature.denominator as u64;
    if den == 0 {
        return 0;
    }
    num * (score.ppq as u64) * 4 / den
}

/// イベント列の最終 tick (Note の end_tick or LoopBlock 末尾) を返す。
fn track_last_tick(events: &[Event]) -> u64 {
    let mut max = 0u64;
    for e in events {
        match e {
            Event::Note { end_tick, .. } => max = max.max(*end_tick),
            Event::LoopBlock {
                start_tick,
                events,
                count,
            } => {
                let one = track_last_tick(events).saturating_sub(*start_tick);
                max = max.max(*start_tick + one * (*count as u64));
            }
        }
    }
    max
}

/// MIDI ノート番号を `(音名文字列, オクターブ)` に変換する。
///
/// lcvgc は `c1`〜`c9` 等の小文字音名 + `#` を使う。オクターブは MIDI 60 = C4
/// 規約に従う。
fn midi_to_note_name(midi: u8) -> (&'static str, u8) {
    let names = [
        "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b",
    ];
    let octave = (midi / 12).saturating_sub(1); // MIDI 60 → 4
    let name = names[(midi % 12) as usize];
    (name, octave)
}

/// GM ドラムマップ。score 内で実際に出現するノートだけ kit に登録するため、
/// 知らないノートは `None` を返す。
fn gm_drum_label(midi: u8) -> Option<&'static str> {
    Some(match midi {
        35 => "bd_acoustic",
        36 => "bd",
        37 => "side_stick",
        38 => "snare",
        39 => "hand_clap",
        40 => "snare_electric",
        41 => "tom_low_floor",
        42 => "hh",
        43 => "tom_high_floor",
        44 => "hh_pedal",
        45 => "tom_low",
        46 => "oh",
        47 => "tom_low_mid",
        48 => "tom_high_mid",
        49 => "crash",
        50 => "tom_high",
        51 => "ride",
        52 => "crash_china",
        53 => "ride_bell",
        54 => "tambourine",
        55 => "crash_splash",
        56 => "cowbell",
        57 => "crash2",
        58 => "vibraslap",
        59 => "ride2",
        60 => "hi_bongo",
        61 => "lo_bongo",
        _ => return None,
    })
}

/// `Event::Note` だけを `(start, end, midi, velocity)` で列挙する (LoopBlock の中も再帰)。
fn iter_notes(events: &[Event]) -> Vec<(u64, u64, u8, u8)> {
    let mut out = Vec::new();
    for e in events {
        match e {
            Event::Note {
                start_tick,
                end_tick,
                midi_note,
                velocity,
            } => out.push((*start_tick, *end_tick, *midi_note, *velocity)),
            Event::LoopBlock { events, .. } => {
                out.extend(iter_notes(events));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generator::score::{Event, Score, TimeSignature, Track, TrackKind};

    fn one_note_score() -> Score {
        Score {
            ppq: 480,
            initial_bpm: 120.0,
            time_signature: TimeSignature::default(),
            title: Some("test".into()),
            tracks: vec![Track {
                name: "lead".into(),
                midi_channel: 1,
                kind: TrackKind::Melodic,
                events: vec![Event::Note {
                    start_tick: 0,
                    end_tick: 480, // 1 拍
                    midi_note: 60, // C4
                    velocity: 100,
                }],
            }],
        }
    }

    #[test]
    fn emit_includes_required_blocks() {
        let dsl = emit(&one_note_score()).unwrap();
        assert!(dsl.contains("device gen_device"));
        assert!(dsl.contains("instrument lead"));
        assert!(dsl.contains("clip lead_clip"));
        assert!(dsl.contains("tempo 120"));
        assert!(dsl.contains("scene gen_scene"));
        assert!(dsl.contains("play gen_scene"));
    }

    #[test]
    fn melodic_clip_has_single_note() {
        let dsl = emit(&one_note_score()).unwrap();
        // C4 / 4 分音符 で書かれる
        assert!(dsl.contains("c:4:4"));
    }

    #[test]
    fn rest_inserted_between_notes() {
        let mut s = one_note_score();
        s.tracks[0].events = vec![
            Event::Note {
                start_tick: 0,
                end_tick: 240, // 8 分
                midi_note: 60,
                velocity: 100,
            },
            Event::Note {
                start_tick: 480, // 4 分目から
                end_tick: 720,   // + 8 分
                midi_note: 62,
                velocity: 100,
            },
        ];
        let dsl = emit(&s).unwrap();
        // 0-240 で c:4:8、240-480 が休符 8 分、480 から d:4:8
        assert!(dsl.contains("c:4:8"));
        assert!(dsl.contains("r:8"));
        assert!(dsl.contains("d:4:8"));
    }

    #[test]
    fn chord_emitted_with_bracket_notation() {
        let mut s = one_note_score();
        // 同 tick で C4 + E4 + G4 を 2 分鳴らす
        s.tracks[0].events = vec![
            Event::Note {
                start_tick: 0,
                end_tick: 960,
                midi_note: 60,
                velocity: 100,
            },
            Event::Note {
                start_tick: 0,
                end_tick: 960,
                midi_note: 64,
                velocity: 100,
            },
            Event::Note {
                start_tick: 0,
                end_tick: 960,
                midi_note: 67,
                velocity: 100,
            },
        ];
        let dsl = emit(&s).unwrap();
        assert!(dsl.contains("[c:4 e:4 g:4]:2"));
    }

    #[test]
    fn loop_block_expands_to_repeat_notation() {
        // (c4:4)*2 を期待する
        let inner = vec![Event::Note {
            start_tick: 0,
            end_tick: 480,
            midi_note: 60,
            velocity: 100,
        }];
        let s = Score {
            tracks: vec![Track {
                name: "lead".into(),
                midi_channel: 1,
                kind: TrackKind::Melodic,
                events: vec![Event::LoopBlock {
                    start_tick: 0,
                    events: inner,
                    count: 2,
                }],
            }],
            ..one_note_score()
        };
        let dsl = emit(&s).unwrap();
        assert!(dsl.contains("*2"), "expected (...)*2 in output:\n{}", dsl);
        assert!(dsl.contains("c:4:4"));
    }

    #[test]
    fn drum_track_emits_kit_and_step_sequencer() {
        // bd (note 36) を 4 つ打ち
        let s = Score {
            tracks: vec![Track {
                name: "drums".into(),
                midi_channel: 10,
                kind: TrackKind::Drum,
                events: vec![
                    Event::Note {
                        start_tick: 0,
                        end_tick: 120,
                        midi_note: 36,
                        velocity: 100,
                    },
                    Event::Note {
                        start_tick: 480,
                        end_tick: 600,
                        midi_note: 36,
                        velocity: 100,
                    },
                    Event::Note {
                        start_tick: 960,
                        end_tick: 1080,
                        midi_note: 36,
                        velocity: 100,
                    },
                    Event::Note {
                        start_tick: 1440,
                        end_tick: 1560,
                        midi_note: 36,
                        velocity: 100,
                    },
                ],
            }],
            ..one_note_score()
        };
        let dsl = emit(&s).unwrap();
        assert!(dsl.contains("kit gen_kit"));
        assert!(dsl.contains("use gen_kit"));
        assert!(dsl.contains("resolution 16"));
        // bd 行に x が 4 ステップ間隔で 4 つ
        assert!(dsl.contains("bd x...x...x...x..."));
    }

    #[test]
    fn note_name_conversion_for_middle_c() {
        let (name, oct) = midi_to_note_name(60);
        assert_eq!(name, "c");
        assert_eq!(oct, 4);
    }

    #[test]
    fn note_name_conversion_for_a4() {
        let (name, oct) = midi_to_note_name(69);
        assert_eq!(name, "a");
        assert_eq!(oct, 4);
    }
}
